### ISSUE TITLE
Meteor 3.0 update

### ISSUE THREAD

**Issue by dallman2** [Meteor-Community-Packages/meteor-timesync#57]
Currently, I have this repo cloned on my machine, with the `api.versionsFrom(["1.12", "2.3"]);` line commented out of `package.js`. This is the only way to allow a meteor 3.0 project to boot while using this package. Are there any plans to update this repo to be compatible with meteor 3.0 and the broader async migration?

**Comment by StorytellerCZ** [comment]
Compat for Meteor 3.0-beta.7 added in release 0.5.5
