### ISSUE TITLE
Uncaught ReferenceError: TimeSync is not defined 

### ISSUE THREAD

**Issue by acamarata** [Meteor-Community-Packages/meteor-timesync#9]
This happened when I copied your user-status demo code into my project on line:

```
Template.status.serverOffset = TimeSync.serverOffset;
```

I can't figure out the issue as the package is there...

**Comment by mikehaney24** [comment]
i'm getting this issue with v0.3.4 on meteor 1.2.1, is anyone else?

**Comment by mikehaney24** [comment]
figure it out -- it's because i was referencing it in a file that's in a shared folder
